import type { Metadata } from "next";
import "./globals.css";
import Header from "./_componets/Header";

export const metadata: Metadata = {
  title: "Projeto Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
