CREATE TABLE "voluntarios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(80) NOT NULL,
  "sobrenome" varchar(50) NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "senha" varchar(255) NOT NULL,
  "telefone" varchar(20) UNIQUE,
  "nascimento" date,
  "biografia" varchar(500) NOT NULL,
  "status" varchar(20)
);

CREATE TABLE "acoes" (
  "id" SERIAL PRIMARY KEY,
  "titulo" varchar(120) NOT NULL,
  "descricao" varchar(300) NOT NULL,
  "url_imagem" varchar(255) NOT NULL,
  "tipo" varchar(255) NOT NULL,
  "id_autor" integer,
  "data_criacao" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "inscricoes" (
  "id" SERIAL PRIMARY KEY,
  "id_voluntario" integer,
  "id_acao" integer,
  "data_inscricao" timestamp DEFAULT (current_timestamp)
);

ALTER TABLE "inscricoes" ADD FOREIGN KEY ("id_voluntario") REFERENCES "voluntarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "acoes" ADD FOREIGN KEY ("id_autor") REFERENCES "voluntarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inscricoes" ADD FOREIGN KEY ("id_acao") REFERENCES "acoes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- =======================================================
-- 🔒 RESTRIÇÕES DE SEGURANÇA (CONSTRAINTS)
-- =======================================================

-- Garante que um voluntário não possa se inscrever duas vezes na mesma ação
ALTER TABLE inscricoes ADD CONSTRAINT unique_voluntario_acao UNIQUE (id_voluntario, id_acao);

-- =======================================================
-- 🧪 POPULAÇÃO INICIAL DE TESTES (SEEDS)
-- =======================================================
-- ATENÇÃO: Os comandos abaixo limpam as tabelas e inserem dados fictícios para testes locais.

-- Limpa dados antigos respeitando a ordem das chaves estrangeiras
DELETE FROM inscricoes;
DELETE FROM acoes;
DELETE FROM voluntarios;

-- Insere Voluntário de Teste (ID 1)
INSERT INTO voluntarios (nome, sobrenome, email, senha, telefone, nascimento, biografia)
VALUES ('Vinicius', 'Dev', 'vinicius@teste.com', '123456', '11999999999', '1995-01-01', 'Desenvolvedor Fullstack');

-- Insere Ação de Teste (ID 1 - Vinculada ao autor ID 1)
INSERT INTO acoes (titulo, descricao, url_imagem, tipo, id_autor)
VALUES ('Ação Teste', 'Descrição da ação de teste', 'http://imagem.com', 'Social', 1);